<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'rainlab\\blog\\Plugin' => 'plugins\\rainlab\\blog\\Plugin.php',
  'RainLab\\Blog\\Models\\Post' => 'plugins\\rainlab\\blog\\models\\Post.php',
  'RainLab\\Blog\\Classes\\TagProcessor' => 'plugins\\rainlab\\blog\\classes\\TagProcessor.php',
  'RainLab\\Blog\\Models\\Category' => 'plugins\\rainlab\\blog\\models\\Category.php',
  'rainlab\\builder\\Plugin' => 'plugins\\rainlab\\builder\\Plugin.php',
  'rainlab\\user\\Plugin' => 'plugins\\rainlab\\user\\Plugin.php',
  'RainLab\\User\\Models\\User' => 'plugins\\rainlab\\user\\models\\User.php',
  'RainLab\\User\\Models\\UserGroup' => 'plugins\\rainlab\\user\\models\\UserGroup.php',
  'RainLab\\User\\Classes\\UserRedirector' => 'plugins\\rainlab\\user\\classes\\UserRedirector.php',
  'vojtasvoboda\\twigextensions\\Plugin' => 'plugins\\vojtasvoboda\\twigextensions\\Plugin.php',
  'ginopane\\blogtaxonomy\\Plugin' => 'plugins\\ginopane\\blogtaxonomy\\Plugin.php',
  'GinoPane\\BlogTaxonomy\\Models\\ModelAbstract' => 'plugins\\ginopane\\blogtaxonomy\\models\\ModelAbstract.php',
  'GinoPane\\BlogTaxonomy\\Models\\Tag' => 'plugins\\ginopane\\blogtaxonomy\\models\\Tag.php',
  'GinoPane\\BlogTaxonomy\\Models\\Series' => 'plugins\\ginopane\\blogtaxonomy\\models\\Series.php',
);